# Generated by Django 5.0.3 on 2024-03-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name_plural": "Profile"},
        ),
        migrations.AlterModelOptions(
            name="profilestatus",
            options={"verbose_name_plural": "Profile_Status"},
        ),
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="profiles_photos/%Y-%m"
            ),
        ),
    ]
